[project]
name = "crowdstrike-foundry-function"
description = "CrowdStrike Foundry Function Software Developer Kit for Python"
requires-python = ">=3.8.0"
dynamic = ['dependencies', 'version']
readme = "README.md"

[build-system]
requires = ['setuptools>=67.7.2']
